### PR TITLE
Add Infrasoft to PQC matrix

### PR DESCRIPTION
**Pull request by HugoBde**
Submitting this pull request on behalf of Infrasoft. Please let us know if anything needs to be amended.

### CODE REVIEW

**Comment by primetomas** [comment]
The diff (files changed) shows all lines in the table changed. I was epxecting only a single added line. How did that happen?
I'm expecting a diff like this: https://github.com/pkic/pqccm/pull/35/files

**Comment by HugoBde** [comment]
I apologise, I noticed the column alignments was messy and made it difficult to edit the document, I can revert this change if needed.

**Comment by HugoBde** [comment]
Ok I think the formatting for the matrix is back to the original. I apologise again for the trouble.

**Comment by primetomas** [comment]
No trouble at all. One question. The text mentions Kyber, but the :clock: marks are on Bike, McEliese and HQC. I looked at this file to check: https://github.com/HugoBde/pqccm/blob/main/_index.md

**Comment by HugoBde** [comment]
Thank you for pointing that out. It's been fixed now.

**Comment by primetomas** [comment]
Thanks for the contribution

**Pull request merged**
